site_name: 黑盒圣经
theme: windmill

nav:
  - Home: index.md
  - 经典:
      - 经典1·名场面:
          - ？6: 经典/经典1·名场面/？6.md
          - 铂金会员事件: 经典/经典1·名场面/铂金会员事件.md
          - 不能太内向: 经典/经典1·名场面/不能太内向.md
          - 不想了: 经典/经典1·名场面/不想了.md
          - 不许说她是: 经典/经典1·名场面/不许说她是.md
          - 干嘛呢: 经典/经典1·名场面/干嘛呢.md
          - 没完没了了是吧: 经典/经典1·名场面/没完没了了是吧.md
          - 你别恩将仇报: 经典/经典1·名场面/你别恩将仇报.md
          - 你和你姨妈就等着过瘾吧: 经典/经典1·名场面/你和你姨妈就等着过瘾吧.md
          - 你属什么: 经典/经典1·名场面/你属什么.md
          - 她似乎带点nt: 经典/经典1·名场面/她似乎带点nt.md
          - 要你微信: 经典/经典1·名场面/要你微信.md
          - 怎么可能看书: 经典/经典1·名场面/怎么可能看书.md
          - 最幸运的事: 经典/经典1·名场面/最幸运的事.md
      - 经典2:
          - 粑粑: 经典/经典2/粑粑.md
          - 比热容: 经典/经典2/比热容.md
          - 不需要: 经典/经典2/不需要.md
          - 藏头诗: 经典/经典2/藏头诗.md
          - 成语接龙: 经典/经典2/成语接龙.md
          - 答应: 经典/经典2/答应.md
          - 到家了: 经典/经典2/到家了.md
          - 多了个儿子: 经典/经典2/多了个儿子.md
          - 腐蚀装: 经典/经典2/腐蚀装.md
          - 改成一号: 经典/经典2/改成一号.md
          - 感觉有点难受: 经典/经典2/感觉有点难受.md
          - 搞笑: 经典/经典2/搞笑.md
          - 给台阶: 经典/经典2/给台阶.md
          - 孤儿: 经典/经典2/孤儿.md
          - 哈喽: 经典/经典2/哈喽.md
          - 和好了: 经典/经典2/和好了.md
          - 黑大帅: 经典/经典2/黑大帅.md
          - 很好看: 经典/经典2/很好看.md
          - 哄你睡: 经典/经典2/哄你睡.md
          - 换一家: 经典/经典2/换一家.md
          - 兼职: 经典/经典2/兼职.md
          - 介意: 经典/经典2/介意.md
          - 今天晚上: 经典/经典2/今天晚上.md
          - 看着表哭: 经典/经典2/看着表哭.md
          - 老师: 经典/经典2/老师.md
          - 买东西吃: 经典/经典2/买东西吃.md
          - 没把你当: 经典/经典2/没把你当.md
          - 没分啊: 经典/经典2/没分啊.md
          - 没人要: 经典/经典2/没人要.md
          - 能吃雪糕哦: 经典/经典2/能吃雪糕哦.md
          - 你没有手嘛: 经典/经典2/你没有手嘛.md
          - 你特么是谁: 经典/经典2/你特么是谁.md
          - 牛奶还要吗: 经典/经典2/牛奶还要吗.md
          - 暖她一整天: 经典/经典2/暖她一整天.md
          - 删了嘛: 经典/经典2/删了嘛.md
          - 谁把我兑换码用了: 经典/经典2/谁把我兑换码用了.md
          - 声音不好听: 经典/经典2/声音不好听.md
          - 双眼全息投影: 经典/经典2/双眼全息投影.md
          - 死了吗: 经典/经典2/死了吗.md
          - 送你了: 经典/经典2/送你了.md
          - 疼: 经典/经典2/疼.md
          - 痛快话: 经典/经典2/痛快话.md
          - 头像: 经典/经典2/头像.md
          - 玩具: 经典/经典2/玩具.md
          - 忘不了: 经典/经典2/忘不了.md
          - 为什么: 经典/经典2/为什么.md
          - 我随孩子姓: 经典/经典2/我随孩子姓.md
          - 喜欢: 经典/经典2/喜欢.md
          - 先别一直发: 经典/经典2/先别一直发.md
          - 先在一起: 经典/经典2/先在一起.md
          - 相亲: 经典/经典2/相亲.md
          - 想吃啥: 经典/经典2/想吃啥.md
          - 辛巴: 经典/经典2/辛巴.md
          - 学长: 经典/经典2/学长.md
          - 要不: 经典/经典2/要不.md
          - 一见钟情: 经典/经典2/一见钟情.md
          - 意下如何: 经典/经典2/意下如何.md
          - 有人先答应了: 经典/经典2/有人先答应了.md
          - 有意思: 经典/经典2/有意思.md
          - 缘分: 经典/经典2/缘分.md
          - 早点认识她: 经典/经典2/早点认识她.md
          - 只是爱他的钱: 经典/经典2/只是爱他的钱.md
          - 至少得6个人: 经典/经典2/至少得6个人.md
          - 种草莓: 经典/经典2/种草莓.md
          - 自闭症: 经典/经典2/自闭症.md
          - 昨晚上分了: 经典/经典2/昨晚上分了.md
          - hs网站: 经典/经典2/hs网站.md
          - p站: 经典/经典2/p站.md
          - rua: 经典/经典2/rua.md
      - 网友制作合集:
          - 网友制作合集1: 经典/网友制作合集/网友制作合集1.md
          - 网友制作合集2: 经典/网友制作合集/网友制作合集2.md
          - 网友制作合集3: 经典/网友制作合集/网友制作合集3.md
          - 网友制作合集4: 经典/网友制作合集/网友制作合集4.md
      - 细节合集:
          - 细节1: 经典/细节合集/细节1.md
          - 细节2: 经典/细节合集/细节2.md
          - 细节3: 经典/细节合集/细节3.md
          - 细节4: 经典/细节合集/细节4.md
          - 细节5: 经典/细节合集/细节5.md
          - 细节6: 经典/细节合集/细节6.md
          - 细节7: 经典/细节合集/细节7.md
          - 细节8: 经典/细节合集/细节8.md
          - 细节9: 经典/细节合集/细节9.md
          - 细节10: 经典/细节合集/细节10.md
          - 细节11: 经典/细节合集/细节11.md
          - 细节12: 经典/细节合集/细节12.md
          - 细节13: 经典/细节合集/细节13.md
          - 细节14: 经典/细节合集/细节14.md
      - 为什么不说话:
          -不说话: 经典/为什么不说话合集/不说话.md
          -你怎么不说话: 经典/为什么不说话合集/你怎么不说话.md
          -为什么不回我: 经典/为什么不说话合集/为什么不回我.md
          -为什么不说话: 经典/为什么不说话合集/为什么不说话.md
  - 2023年:
      - 4月:
          - 电话线: 2023年/4月/电话线.md
      - 5月:
          - 拉一个群: 2023年/5月/拉一个群.md
          - 你可真有趣: 2023年/5月/你可真有趣.md
          - 突然不想谈了: 2023年/5月/突然不想谈了.md
          - 我觉得不是嘴瓢: 2023年/5月/我觉得不是嘴瓢.md
          - 删好了吗: 2023年/5月/删好了吗.md
